### ISSUE TITLE
buildtool -G Ninja -p doesn't work as expected

### ISSUE THREAD

**Issue by eflumerf** [FNALssi/cetmodules#7]
I'm having issues using the Ninja generator with buildtool, where if I do a second build with no changes to the source, buildtool skips the package stage with an error:
```
------------------------------------
INFO: stage package for artdaq_core v3_09_10 SKIPPED - target package not configured
------------------------------------
```

However, running `ninja package` correctly produces the bz2 file and sha hash.

**Comment by greenc-FNAL** [comment]
Is this a standalone build or within MRB? Could you please include instructions to reproduce?

**Comment by eflumerf** [comment]
This was a standalone build, but now I can't reproduce it manually (I was using a script to build)...

**Comment by greenc-FNAL** [comment]
Please feel free to resubmit if this crops up again.
